# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CompanyGeocoder
                                 A QGIS plugin
 A small geocode to find companys by address (QGIS test plugin)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-04-13
        copyright            : (C) 2022 by Alex Wieschmann (GIS-Akademie)
        email                : wieschmann@gis-akademie.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CompanyGeocoder class from file CompanyGeocoder.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .company_geocoder import CompanyGeocoder
    return CompanyGeocoder(iface)
